config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :archive_queries, only: %i[index show]
  resources :search_queries do
    resources :locations, only: %i[update show] do
      member do
        get :download
      end
    end
    member do
      get :log
      get :download
    end
  end
  root 'search_queries#index'
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  acts_as_token_authentication_handler_for User
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Hawthorn Reestr Service', root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <% if user_signed_in? %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Запросы', search_queries_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Архив', archive_queries_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <div class="nav-link">
            <%= current_user.email %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to t(".sign_out"), destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      </ul>
    <% else %>
      <ul class="navbar-nav ml-auto">
        <%= render "devise/shared/links" %>
      </ul>
    <% end %>
  </div>
</nav>

app/views/application/_notice.html.erb
<div class="alert alert-<%= type %> alert-dismissible fade show" role="alert">
  <%= text %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/application/_notices.html.erb
<% if notice %>
  <%= render partial: "notice", locals: {text: notice, type: 'success'} %>
<% elsif alert %>
  <%= render partial: "notice", locals: {text: alert, type: 'danger'} %>
<% end %>