config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :archive_queries, only: %i[index show]
  resources :search_queries do
    resources :locations, only: %i[update show] do
      member do
        get :download
      end
    end
    member do
      get :log
      get :download
    end
  end
  root 'search_queries#index'
end

app/models/search_query.rb
# frozen_string_literal: true

class SearchQuery
  include Mongoid::Document
  include Mongoid::Timestamps
  field :title, type: String
  field :status, type: String, default: 'process'
  field :archive, type: Boolean, default: false
  field :log_path, type: String, default: ''
  field :pdf_url_all, type: String
  field :zip_url_all, type: String
  field :xml_url_all, type: String
  field :zip_url_apartament, type: String
  field :zip_url_other, type: String
  belongs_to :user
  embeds_many :locations
  accepts_nested_attributes_for :locations
  after_save :remove_finished
  scope :archive, -> { where(archive: true) }
  scope :active, -> { where(archive: false) }

  def log
    File.exist?(log_path) ? File.read(log_path) : 'Нет доступных журналов'
  end

  def counter
    wait_status = ['запуск', 'в обработке']
    done_status = %w[готово ошибка закончено]
    total = locations.inject(0) { |sum, loc| wait_status.any?(loc.status) ? sum : sum + 1 }
    "#{total}/#{locations.count}"
  end

  def complite?
    status.eql? 'success'
  end

  private

  def remove_finished
    locations.each do |location|
      location.delete if location.status == 'закончено'
    end
  end
end

app/controllers/search_queries_controller.rb
# frozen_string_literal: true

class SearchQueriesController < ApplicationController
  before_action :set_search_query, only: %i[show destroy update log download]

  skip_before_action :verify_authenticity_token
  # GET /search_queries
  # GET /search_queries.json
  def index
    @search_queries = current_user.search_query.active.order_by(:created_at.desc)
  end

  # GET /search_queries/1
  # GET /search_queries/1.json
  def show; end

  # GET /search_queries/new
  def new
    @search_query = current_user.search_query.new
  end

  # POST /search_queries
  # POST /search_queries.json
  def create
    @search_query = current_user.search_query.new(search_query_params)
    respond_to do |format|
      if @search_query.save
        format.html { redirect_to @search_query, notice: 'Search query was successfully created.' }
        format.json { render :show, status: :created, location: @search_query }
      else
        format.html { render :new }
        format.json { render json: @search_query.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH /search_queries/1
  # PATCH /search_queries/1.json
  def update
    if @search_query.update(search_query_params)
      UserMailer.with(user: current_user, search_query: @search_query).rosreesrt_request_done.deliver if @search_query.complite?
      render :show, status: :ok, location: @search_query
    else
      render json: @search_query.errors, status: :unprocessable_entity
    end
  end

  # DELETE /search_queries/1
  # DELETE /search_queries/1.json
  def destroy
    @search_query.destroy
    respond_to do |format|
      format.html { redirect_to search_queries_url, notice: 'Search query was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def log
    render json: { log: @search_query.log }
  end

  def download
    pdf_file = @search_query.pdf_url_all
    send_file pdf_file, disposition: 'attachment'
  rescue StandardError => e
    flash[:alert] = "Error: #{e.message}"
    redirect_to root_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_search_query
    @search_query = SearchQuery.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def search_query_params
    params
      .require(:search_query)
      .permit(
        :archive,
        :title,
        :status,
        :pdf_url_all,
        :zip_url_all,
        :xml_url_all,
        :zip_url_apartament,
        :zip_url_other,
        locations_attributes: %i[
          id
          kdastr_id
          use_kdastr
          region
          district
          populated_area
          street_type
          street_name
          house_number
          apartment
          zip_url
          status
          search_uid
        ]
      )
  end
end

app/views/search_queries/_form.html.erb
<%= form_with(model: search_query, local: true) do |form| %>
  <% if search_query.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(search_query.errors.count, "error") %>
        prohibited this search_query from being saved:</h2>

      <ul>
        <% search_query.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="btn-group" role="group" aria-label="Basic example">
    <div class="btn btn-outline-secondary" onClick="javascript:window.location.href='/search_queries/new?kdasrt=true'">Кадастр</div>
    <div class="btn btn-outline-secondary" onClick="javascript:window.location.href='/search_queries/new'">Адрес</div>
  </div>

  <div class="form-group">
    <%= form.label 'Описание запроса' %>
    <%= form.text_field :title, placeholder: 'Дело № 11', class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <label for="address / район:">Введите адрес:</label>
    <input id="address" name="address" type="text" class="form-control" />
  </div>
  <br>
  <%= form.nested_fields_for :locations, Location.new do |location_form| %>
    <div class="panel">

      <div class="form-group">
        <%= location_form.label 'Регион / район:' %>
        <%= location_form.text_field :region, id: 'region', class: 'form-control', required: true, readonly: true %>
      </div>

      <% if params[:kdasrt] %>
        <div class="form-group">
          <%= location_form.label 'Кадастровый номер' %>
          <%= location_form.text_field :kdastr_id, placeholder: 'Кадастровый номер', class: 'form-control', required: true %>
          <%= location_form.hidden_field :use_kdastr, value: true %>
        </div>
      <% else %>

        <div class="form-group">
          <%= location_form.label 'Город / населенный пункт' %>
          <%= location_form.text_field :district, id: 'town', class: 'form-control', required: true, readonly: true %>
        </div>

        <div class="form-group">
          <%= location_form.label 'Улица' %>
          <%= location_form.text_field :street_name, id: 'street', class: 'form-control', required: true, readonly: true %>
        </div>

        <div class="form-gdisabledroup">
          <%= location_form.label 'Тип улицы' %>
          <%= location_form.text_field :street_type, id: 'street_type', class: 'form-control', required: true, readonly: true %>
        </div>

        <div class="form-group">
          <%= location_form.label 'Дом' %>
          <%= location_form.text_field :house_number, id: 'house', class: 'form-control', required: true, readonly: true %>
        </div>

        <div class="form-group">
          <%= location_form.label 'Квартира' %>
          <%= location_form.text_field :apartment, id: 'flat', class: 'form-control', readonly: true %>
        </div>

      <% end %>
    </div>
  <% end %>
  <br>

  <div class="actions">
    <%= form.submit 'Создать запрос', class: 'btn btn-outline-success' %>
  </div>
<% end %>
<script type="text/javascript">

function join(arr /*, separator */) {
  var separator = arguments.length > 1 ? arguments[1] : ", ";
  return arr.filter(function(n){return n}).join(separator);
}

function showRegion(address) {
  $("#region").val(join([address.region, address.region_type_full], " "));
}

function showCity(address) {
  $("#town").val(address.city);
}

function showStreetType(address) {
  $("#street_type").val(address.street_type_full);
}

function showStreet(address) {
  $("#street").val(address.street);
}

function showHouse(address) {
  $("#house").val(join([
    address.house,
    address.block
  ]));
}

function showFlat(address) {
  $("#flat").val(address.flat);
}

function showSelected(suggestion) {
  var address = suggestion.data;
  showRegion(address);
  showCity(address);
  showStreet(address);
  showStreetType(address);
  showHouse(address);
  showFlat(address);
}

$("#address").suggestions({
  token: "<%= [ 'ae6ed2054f8821f87cd3edecd103f24f09ca59a7', 'c35ed7c545a7d91ff5e0b13924a2aa5326917744'].sample %>",
  type: "ADDRESS",
  onSelect: showSelected
});
</script>

app/views/search_queries/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-auto  mr-auto">
      <h3>Список запросов</h3>
    </div>
    <div class="col-auto">
      <%= link_to 'Новый запрос', new_search_query_path, class: 'btn btn-outline-success' %>
    </div>
  </div>
</div>

<br>
<% @search_queries.each do |search_query| %>
  <div class="card">
    <div class="card-body">
      <span class="badge float-sm-right"><%= "#{search_query.status} - #{search_query.counter}" %></span>
      <h5 class="card-title"><%= link_to search_query.title, search_query, class: 'card-link' %></h5>
      <h6 class="card-subtitle mb-2 text-muted"><%= l search_query.created_at, format: :short %></h6>
      <br>
      <a data-toggle="collapse" href="#collapse_list_<%= search_query.id.to_s %>">Адреса</a>
      <ul class="list-group collapse" id="collapse_list_<%= search_query.id.to_s %>">
        <% search_query.locations.each do |location| %>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <%= location.full_address %>
            <span class="badge"><%= location.status %></span>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <br>
<% end %>

app/views/search_queries/new.html.erb
<h1>Новый запрос</h1>

<%= render 'form', search_query: @search_query %>

<%= link_to 'Назад', search_queries_path %>

app/views/search_queries/show.html.erb
<p>
  id:
   <strong><%= @search_query.id.to_s %></strong>
</p>

<p>
  <span class="badge"><%= "#{@search_query.status} - #{@search_query.counter}" %></span>
</p>

<p>
    Название:
<strong>
  <%= @search_query.title %>
</strong>
</p>

<%= form_for @search_query do |f| %>
  <%= f.hidden_field :archive, value: true %>
  <div class="btn-group" role="group" aria-label="Basic example">
    <%= link_to 'PDF',  download_search_query_path(@search_query), class: 'btn btn-outline-primary' %>
    <%= f.submit 'В архив', class: 'btn btn-outline-warning' %>
    <%= link_to 'Удаление', @search_query, class: 'btn btn-outline-danger', method: :delete, data: {confirm: 'Are you sure?'} %>
  </div>
<% end %>

<p>
    Адрес:
<ul>
  <% @search_query.locations.each do |location| %>
    <li>
      <span class="badge"><%= location.status %></span>
      <%= location.full_address %>
    </li>
    <br>
    <div class="btn-group" role="group">
      <%= link_to 'Детали', search_query_location_path(@search_query, location), class: 'btn btn-outline-info' %>
      <%= link_to 'Скачать', download_search_query_location_path(@search_query, location), class: 'btn btn-outline-primary' %>
     </div>
  <% end %>
</ul>
</p>

<p>
  <button id="log_btn" data-toggle="collapse" class="btn btn-outline-secondary" data-target="#show_logs">
    Журнал событий
  </button>
</p>
<div id="show_logs" class="collapse">
  <pre id='logs'>
  </pre>
</div>
<script>
    $("#log_btn").click(function () {
        var search_query_id = '<%= @search_query.id %>'
        $.getJSON("/search_queries/" + search_query_id + "/log.json", function (data) {
            console.log(data);
            $("#logs").text(data.log);
        });
    });
</script>

<%= link_to 'Назад', search_queries_path, class: 'btn btn-outline-success' %>