config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :archive_queries, only: %i[index show]
  resources :search_queries do
    resources :locations, only: %i[update show] do
      member do
        get :download
      end
    end
    member do
      get :log
      get :download
    end
  end
  root 'search_queries#index'
end

app/models/location.rb
# frozen_string_literal: true

class Location
  include Mongoid::Document
  include Mongoid::Timestamps

  field :kdastr_id, type: String # optional
  field :use_kdastr, type: Boolean, default: false # optional
  field :region, type: String
  field :district, type: String # optional
  field :populated_area, type: String # optional
  field :street_type, type: String
  field :street_name, type: String
  field :house_number, type: String
  field :apartment, type: String
  field :zip_url, type: String
  field :status, type: String, default: 'запуск'
  field :search_uid, type: String
  field :root_path, type: String, default: ''
  field :pdf_url, type: String
  field :xml_url, type: String
  field :short_address, type: String
  field :object_type, type: String

  embedded_in :search_query
  # validates :region, :street_type, :street_name, :house_number, :apartment, :zip_url, presence: true
  def full_address
    "#{region}, #{district}, #{street_type} #{street_name}, д. #{house_number} кв. #{apartment}"
  end
end

app/controllers/locations_controller.rb
# frozen_string_literal: true

class LocationsController < ApplicationController
  before_action :set_location, only: %i[index show update download log]
  skip_before_action :verify_authenticity_token
  # GET /locations
  # GET /locations.json
  def index
    @locations = @search_query.locations
  end

  # GET /locations/1
  # GET /locations/1.json
  def show; end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    if @location.update(location_params)
      render :show, status: :ok, local: @location
    else
      render json: @location.errors, status: :unprocessable_entity
    end
  end

  def download
    zip_file = @location.root_path
    if File.exist? zip_file
      send_file zip_file, disposition: 'attachment'
    else
      flash[:alert] = 'File not found'
      redirect_to root_path
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_location
    @search_query = SearchQuery.find(params[:search_query_id])
    @location = @search_query.locations.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def location_params
    params
      .require(:location)
      .permit(
        :kdastr_id,
        :use_kdastr,
        :region,
        :district,
        :populated_area,
        :street_type,
        :street_name,
        :house_number,
        :apartment,
        :zip_url,
        :status,
        :search_uid,
        :log_path,
        :root_path,
        :pdf_url,
        :xml_url,
        :short_address,
        :object_type
      )
  end
end

app/views/locations/show.html.erb
<p><span class="badge"><%= @location.status %></span></p>
<p>id: <strong><%= @location.id.to_s %></strong></p>
<p>Использовать кадастр: <strong><%= @location.use_kdastr %></strong></p>
<p>Кадастр: <strong><%= @location.kdastr_id %></strong></p>
<p>Область: <strong><%= @location.region %></strong></p>
<p>Город / населенный пункт: <strong><%= @location.district %></strong></p>
<p>Населенный пункт: <strong><%= @location.populated_area %></strong></p>
<p>Тип улицы: <strong><%= @location.street_type %></strong></p>
<p>Улица: <strong><%= @location.street_name %></strong></p>
<p>Дом: <strong><%= @location.house_number %></strong></p>
<p>Квартира: <strong><%= @location.apartment %></strong></p>
<p>Поиск uid: <strong><%= @location.search_uid %></strong></p>
<p>Скачать
  - <%= link_to 'Архив', download_search_query_location_path(@search_query, @location), class: 'btn btn-outline-primary' %>
</p>
<%= link_to "Назад", search_query_path(@search_query), class: 'btn btn-outline-success' %>